language: cpp

env:
  global:
    - LANG="zh_CN.UTF-8"
    - CMAKE_PREFIX=$HOME/prebuilt/cmake ;
    - CMAKE_VERSION=3.4.3 ;
  matrix:
    - TRAVIS_OS_NAME=osx CC=clang CXX=clang
    - TRAVIS_OS_NAME=osx CC=gcc CXX=gcc
    - TRAVIS_OS_NAME=linux CC=gcc CXX=gcc
    - TRAVIS_OS_NAME=linux CC=gcc-4.9 CXX=g++-4.9
    - TRAVIS_OS_NAME=linux CC=clang-3.6 CXX=clang++-3.6

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm-upper; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update -qq; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
  
install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$CC" == "gcc-4.9" ] ; then sudo apt-get install -qq gcc-4.9-multilib g++-4.9-multilib; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$CC" == "clang-3.6" ] ; then sudo apt-get install --allow-unauthenticated -qq clang-3.6; fi

before_script:
  - REPO_DIR=$PWD;
  - mkdir -p tools && cd tools ;
  - if [ ! -e "$CMAKE_PREFIX/bin/cmake" ]; then
        wget -c "https://github.com/Kitware/CMake/archive/v$CMAKE_VERSION.tar.gz" -O CMake-$CMAKE_VERSION.tar.gz ;
        tar -axvf CMake-$CMAKE_VERSION.tar.gz > build_cmake.log 2>&1 ;
        cd CMake-$CMAKE_VERSION ;
        ./bootstrap --prefix=$CMAKE_PREFIX  >> build_cmake.log 2>&1 ;
        make -j4 install  >> build_cmake.log 2>&1 ;
    fi
  - mkdir -p $REPO_DIR/build && cd $REPO_DIR/build ;
  - $CMAKE_PREFIX/bin/cmake .. -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX ;

after_success:
  - test/unit_test
  
script: 
  - make -j4

install: true

cache: 
  - apt
  - directories:
    - $CMAKE_PREFIX
    
branches:
  only:
    - master

notifications:
  email: false
  irc:
    template:
      - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"
