#
# Appveyor configuration file for CI build of hiredis-happ on Windows (under Cygwin)
#
# For further details see http://www.appveyor.com
#

#
# Custom environment variables
#
environment:
    global:
        PREBUILT_ROOT: C:/Users/appveyor/prebuilt
        SETUP_ROOT: C:/Users/appveyor/setup
        PKG_SRC_ROOT: C:/Users/appveyor/pkg_src
        LIBUV_VERSION: 1.8.0
    matrix:
        - os: Visual Studio 2015
          platform: x64
          LIBUV_PKG: http://dist.libuv.org/dist/v1.8.0/libuv-x64-v1.8.0.build8.exe
          LIBUV_ROOT: C:/Users/appveyor/prebuilt/x64/1.8.0
          CMAKE_GEN: Visual Studio 14 2015 Win64
        - os: Visual Studio 2013
          platform: x64
          LIBUV_PKG: http://dist.libuv.org/dist/v1.8.0/libuv-x64-v1.8.0.build8.exe
          LIBUV_ROOT: C:/Users/appveyor/prebuilt/x64/1.8.0
          CMAKE_GEN: Visual Studio 12 2013 Win64
        - os: MinGW
          LIBUV_PKG: http://dist.libuv.org/dist/v1.8.0/libuv-v1.8.0.tar.gz
          LIBUV_ROOT: C:/Users/appveyor/prebuilt/mingw/1.8.0

configuration: RelWithDebInfo
    
#
# Cache Cygwin files to speed up build
#
cache:
    - C:\Users\appveyor\setup
    - C:\Users\appveyor\prebuilt
    - C:\Users\appveyor\pkg_src

#
# Do a shallow clone of the repo to speed up build
#
clone_depth: 1

#
# Initialisation prior to pulling the Mono repository
# Attempt to ensure we don't try to convert line endings to Win32 CRLF as this will cause build to fail
#
init:
    - git config --global core.autocrlf input

#
# Install needed build dependencies
# 
install:
    - ps: >-
        if ( -not ( Test-Path "$Env:LIBUV_ROOT" ) ) { 
            
            mkdir "$Env:LIBUV_ROOT"
            
        }
        
        if ( -not ( Test-Path "$Env:SETUP_ROOT" ) ) { 
            
            mkdir "$Env:SETUP_ROOT"
            
        }
        
        if ( -not ( Test-Path "$Env:PKG_SRC_ROOT" ) ) { 
            
            mkdir "$Env:PKG_SRC_ROOT"
            
        }
        
        if ( "$Env:OS" -ieq "MinGW" ) {
            
            & C:\MinGW\bin\mingw-get install msys-automake msys-autoconf msys-m4 msys-tar msys-wget msys-libtool mingw32-automake mingw32-autoconf mingw32-libtool mingw32-gcc-tools
            
            $LIBUV_PKG_PATH="$Env:SETUP_ROOT/libuv-v$Env:LIBUV_VERSION.tar.gz"
            
            $LIBUV_TAR_PATH="$Env:SETUP_ROOT/libuv-v$Env:LIBUV_VERSION.tar"
            
            if ( Test-Path "$LIBUV_PKG_PATH" ) {
                
                echo "using cache $LIBUV_PKG_PATH"   
                
            } else {
                
                Invoke-WebRequest "$Env:LIBUV_PKG" -OutFile "$LIBUV_PKG_PATH"
                
            }
            
            echo "7z x -o'$Env:PKG_SRC_ROOT' '$LIBUV_PKG_PATH'" 
            
            & 7z x -o"$Env:SETUP_ROOT" "$LIBUV_PKG_PATH"
            
            echo "7z x -o'$Env:PKG_SRC_ROOT' '$LIBUV_TAR_PATH'" 
            
            & 7z x -o"$Env:PKG_SRC_ROOT" "$LIBUV_TAR_PATH"
            
            echo "bash -lc cd '$Env:PKG_SRC_ROOT/libuv-v$Env:LIBUV_VERSION' && ./autogen.sh && ./configure --prefix=$Env:LIBUV_ROOT --with-pic=yes --enable-shared=no --enable-static=yes && make install" 
            
            & bash -lc "cd '$Env:PKG_SRC_ROOT/libuv-v$Env:LIBUV_VERSION' && ./autogen.sh && ./configure --prefix=$Env:LIBUV_ROOT --with-pic=yes --enable-shared=no --enable-static=yes && make install"
            
        } else {
            if ( Test-Path "$Env:LIBUV_ROOT/libuv.dll" ) {
                
                echo "using prebuilt cache $Env:LIBUV_ROOT" 
                
            } else {
                
                $LIBUV_PKG_PATH="$Env:SETUP_ROOT/libuv-$Env:PLATFORM-$Env:LIBUV_VERSION.exe"
                
                if ( Test-Path "$LIBUV_PKG_PATH" ) {
                    
                    echo "using cache $LIBUV_PKG_PATH"   
                    
                } else {
                    
                    Invoke-WebRequest "$Env:LIBUV_PKG" -OutFile "$LIBUV_PKG_PATH"
                    
                }
                
                echo "7z x -o'$Env:LIBUV_ROOT' '$LIBUV_PKG_PATH'" 
                
                & 7z x -o"$Env:LIBUV_ROOT" "$LIBUV_PKG_PATH"
            }
        }

# Build script
#
# NOTES:
#
# The stdin/stdout file descriptor appears not to be valid for the Appveyor
# build which causes failures as certain functions attempt to redirect 
# default file handles. Ensure a dummy file descriptor is opened with 'exec'.
#
build_script:
    - ps: >- 
        mkdir build
        
        cd build
        
        Remove-Item -r *
        
        if ( "$Env:OS" -ieq "MinGW" ) {
            
            echo "cmake .. -G 'MSYS Makefiles' -DLIBUV_ROOT='$Env:PKG_SRC_ROOT/libuv-v$Env:LIBUV_VERSION'" 
            
            & cmake .. -G "MSYS Makefiles" -DLIBUV_ROOT="$Env:PKG_SRC_ROOT/libuv-v$Env:LIBUV_VERSION"
            
            & bash -lc "make -j4"
            
        } else {
            
            echo "cmake ..  -G '$Env:CMAKE_GEN' -DLIBUV_ROOT='$Env:LIBUV_ROOT'" 
            
            & cmake ..  -G "$Env:CMAKE_GEN" -DLIBUV_ROOT="$Env:LIBUV_ROOT"
            
            echo "'C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe' 'libatbus.sln' /verbosity:minimal /p:Configuration=$Env:CONFIGURATION /p:Platform=$Env:PLATFORM"
            
            & "C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe" "libatbus.sln" /verbosity:minimal /p:Configuration=$Env:CONFIGURATION /p:Platform=$Env:PLATFORM
        }
#
# Run unit test
# 
test_script:
    - ps: >- 
        if ( "$Env:OS" -ieq "MinGW" ) {
            
            & bash -lc "./test/unit_test.exe"
            
        } else {
            
            Copy-Item -Force "$Env:LIBUV_ROOT/libuv.dll" ./
            
            & "test/$Env:CONFIGURATION/unit_test.exe"
        }

#
# Only build the master branch
#
branches:
  only:
    - master

# no need artifacts
